on:
  push:
    branches:
      - pre-release
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - run: echo 안녕, pre-release!
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action